export const UPDATE_DONORS_DATA = "UPDATE_DONORS_DATA";
export const GET_ALL_BLOOD_TYPE = "GET_ALL_BLOOD_TYPE";
export const GET_ALL_STATES_INDIA = "GET_ALL_STATES_INDIA";
export const GET_CITY_BY_STATE = "GET_CITY_BY_STATE";
export const GET_ALL_FEED = "GET_ALL_FEED";
export const GET_ALL_NOTIFICATION = "GET_ALL_NOTIFICATION";
export const GET_ALL_REQUEST = "GET_ALL_REQUEST";
export const GET_ALL_REQUEST_By_USER = "GET_ALL_REQUEST_By_USER";
